version: "3.7"
services:
  database:
    image: postgres
    env_file:
      - application.env
    ports: 
      - "5442:5432"
    volumes: 
      - boiler-plate-data:/var/lib/postgres/data
        
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - application.env
    depends_on: 
      - database
    ports: 
      - "8080:8080"
volumes:
  boiler-plate-data:

